// Temporary Mock Data for Frontend Testing
// TODO: Replace with backend API integration
export const MOCK_STATIONS = [
  // QUEZON CITY
  {
    id: "mock-qc-1",
    name: "Petron Quezon Avenue",
    brand: "Petron",
    city: "Quezon City",
    address: "Quezon Ave cor. Timog Ave, Quezon City",
    distance: 0.5,
    verified: true,
    lastUpdated: "2 hours ago",
    lat: 14.636,
    lng: 121.037,
    prices: [
      { type: "Diesel", price: 55.30 },
      { type: "Premium Diesel", price: 59.50 },
      { type: "Unleaded 91", price: 64.50 },
      { type: "Premium 95", price: 68.20 },
      { type: "Premium 97", price: 72.80 },
      { type: "Kerosene", price: 52.40 },
    ],
  },
  {
    id: "mock-qc-2",
    name: "Shell EDSA Cubao",
    brand: "Shell",
    city: "Quezon City",
    address: "EDSA Southbound, Cubao, Quezon City",
    distance: 1.2,
    verified: true,
    lastUpdated: "4 hours ago",
    lat: 14.620,
    lng: 121.052,
    prices: [
      { type: "Diesel", price: 56.10 },
      { type: "Premium Diesel", price: 60.20 },
      { type: "Unleaded 91", price: 65.10 },
      { type: "Premium 95", price: 69.00 },
      { type: "Premium 97", price: 73.20 },
      { type: "Kerosene", price: 53.10 },
    ],
  },
  {
    id: "mock-qc-3",
    name: "Caltex Commonwealth",
    brand: "Caltex",
    city: "Quezon City",
    address: "Commonwealth Ave, Diliman, Quezon City",
    distance: 2.1,
    verified: false,
    lastUpdated: "1 day ago",
    lat: 14.654,
    lng: 121.062,
    prices: [
      { type: "Diesel", price: 54.80 },
      { type: "Premium Diesel", price: 58.90 },
      { type: "Unleaded 91", price: 63.80 },
      { type: "Premium 95", price: 67.50 },
      { type: "Premium 97", price: 71.90 },
      { type: "Kerosene", price: 51.80 },
    ],
  },
  {
    id: "mock-qc-4",
    name: "Seaoil Timog",
    brand: "Seaoil",
    city: "Quezon City",
    address: "Timog Ave, Diliman, Quezon City",
    distance: 1.8,
    verified: true,
    lastUpdated: "5 hours ago",
    lat: 14.633,
    lng: 121.039,
    prices: [
      { type: "Diesel", price: 54.50 },
      { type: "Premium Diesel", price: 58.20 },
      { type: "Unleaded 91", price: 63.20 },
      { type: "Premium 95", price: 66.90 },
      { type: "Premium 97", price: 71.50 },
      { type: "Kerosene", price: 51.00 },
    ],
  },

  // MAKATI
  {
    id: "mock-makati-1",
    name: "Petron Makati Ave",
    brand: "Petron",
    city: "Makati",
    address: "Makati Ave cor. Jupiter St, Makati",
    distance: 3.5,
    verified: true,
    lastUpdated: "1 hour ago",
    lat: 14.563,
    lng: 121.031,
    prices: [
      { type: "Diesel", price: 57.00 },
      { type: "Premium Diesel", price: 61.20 },
      { type: "Unleaded 91", price: 66.50 },
      { type: "Premium 95", price: 70.00 },
      { type: "Premium 97", price: 74.00 },
      { type: "Kerosene", price: 54.00 },
    ],
  },
  {
    id: "mock-makati-2",
    name: "Shell Buendia",
    brand: "Shell",
    city: "Makati",
    address: "Sen. Gil Puyat Ave, Makati",
    distance: 4.2,
    verified: true,
    lastUpdated: "3 hours ago",
    lat: 14.558,
    lng: 121.025,
    prices: [
      { type: "Diesel", price: 57.80 },
      { type: "Premium Diesel", price: 62.00 },
      { type: "Unleaded 91", price: 67.10 },
      { type: "Premium 95", price: 71.00 },
      { type: "Premium 97", price: 75.20 },
      { type: "Kerosene", price: 54.80 },
    ],
  },
  {
    id: "mock-makati-3",
    name: "Cleanfuel Chino Roces",
    brand: "Cleanfuel",
    city: "Makati",
    address: "Chino Roces Ave, Makati",
    distance: 3.8,
    verified: false,
    lastUpdated: "2 days ago",
    lat: 14.550,
    lng: 121.015,
    prices: [
      { type: "Diesel", price: 56.50 },
      { type: "Premium Diesel", price: 60.50 },
      { type: "Unleaded 91", price: 65.50 },
      { type: "Premium 95", price: 69.50 },
      { type: "Premium 97", price: 73.50 },
      { type: "Kerosene", price: 53.50 },
    ],
  },

  // PASAY
  {
    id: "mock-pasay-1",
    name: "Caltex Macapagal",
    brand: "Caltex",
    city: "Pasay",
    address: "Macapagal Blvd, Pasay",
    distance: 6.5,
    verified: true,
    lastUpdated: "4 hours ago",
    lat: 14.535,
    lng: 120.988,
    prices: [
      { type: "Diesel", price: 55.50 },
      { type: "Premium Diesel", price: 59.50 },
      { type: "Unleaded 91", price: 64.50 },
      { type: "Premium 95", price: 68.50 },
      { type: "Premium 97", price: 72.50 },
      { type: "Kerosene", price: 52.50 },
    ],
  },
  {
    id: "mock-pasay-2",
    name: "Shell NAIAx",
    brand: "Shell",
    city: "Pasay",
    address: "NAIAx Terminal 3, Pasay",
    distance: 7.2,
    verified: true,
    lastUpdated: "Just now",
    lat: 14.520,
    lng: 121.015,
    prices: [
      { type: "Diesel", price: 56.20 },
      { type: "Premium Diesel", price: 60.20 },
      { type: "Unleaded 91", price: 65.20 },
      { type: "Premium 95", price: 69.20 },
      { type: "Premium 97", price: 73.20 },
      { type: "Kerosene", price: 53.20 },
    ],
  },
  {
    id: "mock-pasay-3",
    name: "Petron Roxas Blvd",
    brand: "Petron",
    city: "Pasay",
    address: "Roxas Blvd, Pasay",
    distance: 5.8,
    verified: false,
    lastUpdated: "6 hours ago",
    lat: 14.542,
    lng: 120.990,
    prices: [
      { type: "Diesel", price: 54.90 },
      { type: "Premium Diesel", price: 58.90 },
      { type: "Unleaded 91", price: 63.90 },
      { type: "Premium 95", price: 67.90 },
      { type: "Premium 97", price: 71.90 },
      { type: "Kerosene", price: 51.90 },
    ],
  },
];
